### ISSUE TITLE
Why Mailtrap is not free?

### ISSUE THREAD

**Issue by le0pard** [jkingsman/Mockbox#18]
> Need to be sure that your automated emails are going out with the content you expect, but don't want to provide your personal SMTP credentials, or want a free alternative to Mailtrap?

This text say, what Mailtrap is not free, but it is not true. Mailtrap have free plan and need pay for bigger number of inboxes, rate limit and forwarding. And this solution use "TO" email header, but Mailtrap - accept emails with any "TO" and "CC" address and not pass to real customers. So this solution even not similar to Mailtrap.

**Comment by jkingsman** [comment]
I would say that they are similar in terms of providing SMTP server simulation. 

You are correct that this is much lighter weight than Mailtrap; that's somewhat of the point - no login, no account management, no tiering. This lets me test something in the field in seconds instead of minutes. Mailtrap is a great service; Mockbox just offers something a little lighter weight. If it doesn't fit your needs, don't use it haha - no one is forcing it on you.

**Comment by le0pard** [comment]
My main disagree - Mailtrap is still free. And more close services for mockbox is https://mailinator.com/, http://maildrop.cc/ (inbox per email)

**Comment by jkingsman** [comment]
I think we're starting to get into semantic hair splitting; certain methods of use for Mailtrap that would identically emulate Mockbox would cost, but you correct that there is a free tier of Mailtrap.

As I said, if Mockbox doesn't fit your needs, don't use it. I'm glad you have something that works for you.
